# Generated by Django 3.2.7 on 2021-09-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('hours_open', models.CharField(max_length=20)),
                ('has_driving_range', models.BooleanField()),
                ('price_9holes_wo_cart', models.IntegerField()),
                ('price_9holes_w_cart', models.IntegerField()),
                ('price_18holes_wo_cart', models.IntegerField()),
                ('price_18holes_w_cart', models.IntegerField()),
            ],
        ),
    ]
